timer
Feruzteame/Time-to-work pull request #5
Opened 2020-09-29 12:58 UTC by Feruzteame

hey guys, here is the timer !

2020-09-30 05:39 UTC, oguzkarademir requested changes

2020-09-30 05:39 UTC, oguzkarademir commented on index.html
> +<script src="src/timer.js"></script>
@Feruzteame we are using export and import, you shouldnt write this script tag

2020-09-30 05:39 UTC, oguzkarademir commented on index.html
> +<script src="src/listener.js"></script>
I guess we need to write the listeners in init.js too, there is no need to listener.js

2020-09-30 05:39 UTC, oguzkarademir commented on src/timer.js
> +let min = 25
We need a class and we need to write properties and methods inside, then we can create new object from this class in handler functions and use these methods.

I checked this codes and it works but timer begin from 25 : 60, how can you fix this

These are my thoughts, thanks for this big work 👏 @Feruzteame

2020-09-30 06:04 UTC, Feruzteame commented on src/timer.js
> +let min = 25
Thank you for your comment actually it is hard to work with class becouse in last module i was't attend my class, that's why i try to do it another way. But i try to fix the second.

2020-09-30 06:05 UTC, Feruzteame commented on src/timer.js
> +let min = 25
May be if you have better idea, welcome!

2020-10-02 15:47 UTC, Feruzteame commented
hi @oguzkarademir  and @miroslavveljanoski  i fix the time(second), now it start with 25:00.

2020-10-16 09:03 UTC, merged